### ISSUE TITLE
UIImage(named:) cannot be used when installed as Pod

### ISSUE THREAD

**Issue by SDPrio** [Guidebook/HideShowPasswordTextField#7]
Hi,

I have just added the pod to my project and it crashed when running it. Problem is, that `UIImage(named:)` cannot/should not be used within a pod. It searches the images within the default / app bundle while it located in the pod bundle. 

Solution 1: Manually add the images to the main app bundle
Solution 2:  Use UIImage(named:in:compatibleWith:) instead

```
let bundle = Bundle(for: PasswordToggleVisibilityView.self)
self.eyeOpenedImage` = UIImage(named: "ic_eye_open", in: bundle, compatibleWith: nil)!.withRenderingMode(.alwaysTemplate)
```

**Comment by miketsprague** [comment]
Thanks @SDPrio, you're absolutely correct! This is now fixed in latest master.

https://github.com/Guidebook/HideShowPasswordTextField/issues/7
